version: "3.6"

services:

  frontend:
    image: nginx:bbr
    container_name: frontend
    ports:
      - 80:80
      - 3300:3300
    environment:
      DOCKER: 'true'
    volumes:
      - ./default-prod.conf:/etc/nginx/conf.d/default.conf
      - ./public:/usr/share/nginx/html
    networks:
      - default

  backend:
    image: ts-backend:prod
    container_name: backend
    environment:
      DOCKER: 'true'
    volumes:
      - ../backend/dist:/usr/src/app/dist
      - ../backend/views:/usr/src/app/views
    restart: always
    networks:
      - default

networks:
  default:
    external:
      name: humle_net
