version: '3.6'

services:
    reverseproxy:
        image: nginx:bbr
        container_name: reverseproxy
        volumes:
          - ./nginx-prod.conf:/etc/nginx/nginx.conf
        ports:
            - 80:80
            - 3300:3300
        restart: always
        networks:
            - default

    frontend:
        image: nginx:bbr
        container_name: frontend
        environment:
          DOCKER: 'true'
        volumes:
            - ./frontend/public:/usr/share/nginx/html
        networks:
            - default

    backend:
        image: ts-backend:prod
        container_name: backend
        environment:
            DOCKER: 'true'
        volumes:
            - ./backend/dist:/usr/src/app/dist
            - ./backend/views:/usr/src/app/views
            - ./static:/usr/src/app/static
        restart: always
        networks:
            - default



networks:
    default:
        external:
            name: humle_net
