version: '3.6'

services:
  backend:
    image: ts-backend:prod
    container_name: backend
    ports:
    - 3300:3300
    environment:
      DOCKER: 'true'
    volumes:
    - ./dist:/usr/src/app/dist
    - ./views:/usr/src/app/views
    - ./public:/usr/src/app/public
    restart: always
    networks:
      - default

networks:
  default:
    external:
      name: humle_net
